### ISSUE TITLE
Using a doxygen style

### ISSUE THREAD

**Issue by ollelogdahl** [satu0king/Github-Documentation-With-Doxygen#2]
Hello,
Im trying to do this and also use another style. Im looking at the 'that_style' right now.
I got it all working, and modified to add a git clone to the working directory. But the that_style directory doesn't seem to be moved over, but instead all files copied to / on the automatic push to gh-pages branch. Any help would be appreciated!

```yml
# This is a basic workflow to help you get started with Actions

name: Doxygen

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: That Style install
      # Clones the 'that_style' into dir that_style/
      run: git clone https://github.com/jl-wynen/that_style.git
    
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "./Doxyfile" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
```

Thanks in advance,
Olle
